#ifndef CUSTOM_BOARD_H
#define CUSTOM_BOARD_H

#define RX_PIN_NUMBER 1
#define TX_PIN_NUMBER 0
#define CTS_PIN_NUMBER 0xFFFFFFFF // NRF_UARTE_PSEL_DISCONNECTED
#define RTS_PIN_NUMBER 0xFFFFFFFF // NRF_UARTE_PSEL_DISCONNECTED

#define BOARD_LED_RED 11

#define BUTTON_PULL    NRF_GPIO_PIN_PULLUP

#define HWFC false

#endif
